name: Build and deploy PHP app to Azure Web App - Chatbotai

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      # Đóng gói trực tiếp toàn bộ source code từ GitHub sang Artifact
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: php-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      # Giải nén thẳng vào thư mục gốc của runner để không bị đẻ ra thư mục con trùng tên
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: php-app
          path: .
        
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8C09FC415C2845C0BBAA1BE84EB36B18 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_DF3E0EBBC6F14A3181AAF2E23A0649E2 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_93060406495E4ED6BEE8258BFA96691B }}

      # Đẩy toàn bộ dữ liệu sạch lên Azure Web App
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'Chatbotai'
          package: .
